<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="assets/css/bootstrap.min.css" rel="stylesheet">

        <title></title>
    </head>
    <body>
        <div class="container">
            <h1>Registre-se gratuitamente</h1>
            <p>Registre-se de forma fácil e rápida. O registro é rápido e grátis.</p>
            <div class="jumbotron">
                <form class="form-horizontal" id="registration">
                    
                    <div class="form-group" id="emailGroup">
                        <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-5">
                            <input type="email" class="form-control" id="inputEmail" placeholder="Email" name="email" onchange="isValidEmailFormat();">
                        </div>
                        <div class="col-sm-5">
                            <span id="helpEmail" class="help-block hidden">Email no formato incorreto.</span>
                            <span id="emailExists" class="help-block hidden">Este Email já encontra-se em nossa base. Digite outro!</span>
                        </div>
                    </div>
                    
                    <div class="form-group" id="confirmEmailGroup">
                        <label for="inputConfirmarEmail" class="col-sm-2 control-label">Confirmar Email</label>
                        <div class="col-sm-5">
                            <input type="email" class="form-control" id="inputConfirmarEmail" placeholder="Confirmar Email"  name="confEmail" onchange="isEqualEmail();">
                        </div>
                        <div class="col-sm-5">
                            <span id="helpConfirmEmail" class="help-block hidden">Email de confirmação esta diferente.</span>
                        </div>
                    </div>
                    
                    <div class="form-group" id='passwordGroup'>
                        <label for="inputPass" class="col-sm-2 control-label">Password</label>
                        <div class="col-sm-5">
                            <input type="password" class="form-control" id="inputPass" placeholder="Password"  name="password" onchange="passStrength();">
                            <span id="helpInfoPass" class="help-block">A senha deve possuir, no mínimo, 6 caracteres contendo, pelo menos uma letra e um número.</span>
                        </div>
                        <div class="col-sm-5">
                            <span id="helpWeak" class="help-block hidden">Sua senha não atende os requisitos.</span>
                            <span id="helpOk" class="help-block hidden">Sua senha atende os requisitos.</span>
                            <span id="helpStrong" class="help-block hidden">Sua senha atende perfeitamente os requisitos.</span>
                        </div>
                    </div>
                    
                    <div class="form-group" id="confirmarPasswordGroup">
                        <label for="inputConfirmarPass" class="col-sm-2 control-label">Confirmar Password</label>
                        <div class="col-sm-5">
                            <input type="password" class="form-control" id="inputConfirmarPass" placeholder="Confirmar Password"  name="conPass" onchange="checkPasswordEqual();">
                        </div>
                        <div class="col-sm-5">
                            <span id="helpConfirmaPasswordError" class="help-block hidden">As duas senhas não são identicas.</span>
                            <span id="helpConfirmaPasswordOk" class="help-block hidden">As duas senhas estão identicas.</span>
                        </div>
                    </div>
                    
                    <div class="form-group" id="gNome">
                        <label for="inputNome" class="col-sm-2 control-label">Nome</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" id="inputNome" name="nome" placeholder="Nome">
                        </div>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" id="inputApelido"  name="apelido" placeholder="Apelido">
                        </div>
                    </div>
                    
                    <div class="form-group" id="gRua">
                        <label for="inputRua" class="col-sm-2 control-label">Rua/No.</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputRua" name="rua"  placeholder="Rua No.">
                        </div>
                    </div>
                    
                    <div class="form-group" id="gCodigo">
                        <label for="inputCodigoPostal" class="col-sm-2 control-label">Código Postal</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" id="inputCodigoPostal" name="codigoPostal"  placeholder="Código Postal">
                        </div>
                        <label for="inputLocalidade" class="col-sm-2 control-label">Localidade</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" id="inputLocalidade" name="localidade"  placeholder="Localidade">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputPais" class="col-sm-2 control-label">País</label>
                        <div class="col-sm-5">
                            <select class="form-control" id="inputPais" name="pais"  onchange="portugalPhoneNumber();">
                                <option value="Portugal">Portugal</option>
                                <option value="Brasil">Brasil</option>
                                <option value="Canada">Canada</option>
                                <option value="Espanha">Espanha</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="form-group" id="gNIF">
                        <label for="inputNIF" class="col-sm-2 control-label">NIF</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" id="inputNIF" name="nif"  placeholder="NIF">
                        </div>
                        <div class="col-sm-5">
                            <span id="nifExists" class="help-block hidden">Este NIF já encontra-se em nossa base!</span>
                        </div>
                    </div>
                    
                    <div class="form-group" id="gTelefone">
                        <label for="inputTelefone" class="col-sm-2 control-label">Telefone</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" id="inputTelefone" name="telefone"  placeholder="Telefone">
                        </div>
                    </div>
                    <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="button" class="btn btn-default" onclick="submitForm()">Registro</button>
                    </div>
                  </div>
                </form>
            </div>
        </div> 
        
        <script src="assets/js/jquery.js"></script>
        <script src="assets/js/maskPlugin.js"></script>
        <script src="assets/js/maskFields.js"></script>
        <script src="assets/js/dataValidation.js"></script>
        <script src="assets/js/bootstrap.min.js"></script>
    </body>
</html>