<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="assets/css/bootstrap.min.css" rel="stylesheet">

        <title></title>
    </head>
    <body>
        <div class="container">
            <h1>Registre-se gratuitamente</h1>
            <p>Registre-se de forma fácil e rápida. O registro é rápido e grátis.</p>
            <div class="jumbotron">
                <form class="form-horizontal">
                    
                    <div class="form-group" id="emailGroup">
                        <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-5">
                            <input type="email" class="form-control" id="inputEmail" placeholder="Email" onchange="isValidEmailFormat();">
                        </div>
                        <div class="col-sm-5">
                            <span id="helpEmail" class="help-block hidden">Email no formato incorreto.</span>
                        </div>
                    </div>
                    
                    <div class="form-group" id="confirmEmailGroup">
                        <label for="inputConfirmarEmail" class="col-sm-2 control-label">Confirmar Email</label>
                        <div class="col-sm-5">
                            <input type="email" class="form-control" id="inputConfirmarEmail" placeholder="Confirmar Email" onchange="isEqualEmail();">
                        </div>
                        <div class="col-sm-5">
                            <span id="helpConfirmEmail" class="help-block hidden">Email de confirmação esta diferente.</span>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputPass" class="col-sm-2 control-label">Password</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="inputPass" placeholder="Password">
                            <span id="helpInfoPass" class="help-block">A senha deve possuir, no mínimo, 8 caracteres contendo, pelo menos 1 letra e .</span>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputConfirmarPass" class="col-sm-2 control-label">Confirmar Password</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="inputConfirmarPass" placeholder="Confirmar Password">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputNome" class="col-sm-2 control-label">Nome</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" id="inputNome" placeholder="Nome">
                        </div>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" id="inputApelido" placeholder="Apelido">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputRua" class="col-sm-2 control-label">Rua No.</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputRua" placeholder="Rua No.">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputCodigoPostal" class="col-sm-2 control-label">Código Postal</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" id="inputCodigoPostal" placeholder="Código Postal">
                        </div>
                        <label for="inputLocalidade" class="col-sm-2 control-label">Localidade</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" id="inputLocalidade" placeholder="Localidade">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputPais" class="col-sm-2 control-label">País</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputPais" placeholder="Pais">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputNIF" class="col-sm-2 control-label">NIF</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputNIF" placeholder="NIF">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="inputTelefone" class="col-sm-2 control-label">Telefone</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputTelefone" placeholder="NIF">
                        </div>
                    </div>
                    <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-default">Sign in</button>
                    </div>
                  </div>
                </form>
            </div>
        </div> 
        
        <script src="assets/js/jquery.js"></script>
        <script src="assets/js/dataValidation.js"></script>
        <script src="assets/js/bootstrap.min.js"></script>
    </body>
</html>