<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="assets/css/bootstrap.min.css" rel="stylesheet">

        <title></title>
    </head>
    <body>
        <div class="container">
            <h1>Registre-se gratuitamente</h1>
            <p>Registre-se de forma fácil e rápida. O registro é rápido e grátis.</p>
            <div class="jumbotron">
                <p>Obrigado por se cadastrar, em breve entraremos em contato</p>
            </div>
        </div>
    </body>
</html>
